baseURL = 'https://faremeter.xyz/'
languageCode = 'en-us'
title = 'Faremeter'
uglyURLs = true

[params]
fullWidthTheme = true
centerTheme = true

[params.logo]
logoText = "Faremeter"

[module]
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v4'
  